Fixed: Re-clicking on Upload file button & cancelling it gives error (#85zrhfp4c)
hotwax/import pull request #143
Opened 2023-01-06 13:12 UTC by k2maan

### Related Issues

Closes #121 

### Short Description and Why It's Useful

Unwanted error is removed, also if we decide not to upload a file, current file says selected.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/import#contribution-guideline)

2023-01-11 09:44 UTC, ymaheshwari1 requested changes

2023-01-11 09:44 UTC, ymaheshwari1 commented on src/views/PurchaseOrder.vue
>          else {
Improve code formatting

2023-01-11 09:44 UTC, ymaheshwari1 commented on src/views/PurchaseOrder.vue
> +          showToast(translate("No new file upload. Please try again"));
Ir works when trying to change the file first time, but if we repeat changing the file more than once, then it does not work.

2023-01-16 05:59 UTC, k2maan commented
After discussion, it is concluded that we'll not implement the functionality to show the toast even after not selecting the file for the first time. The toast will appear only for the first time.

2023-02-01 07:22 UTC, adityasharma7 approved these changes

2023-02-01 07:22 UTC, merged