Added: service endpoints for create, delete and update mappings(#85zrhcq56)
hotwax/import pull request #159
Opened 2023-01-27 04:14 UTC by ymaheshwari1

### Related Issues

Closes #129 

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/import#contribution-guideline)

2023-01-31 11:12 UTC, disha1202 approved these changes
LGTM 👍🏻

2023-02-01 10:03 UTC, adityasharma7 requested changes

2023-02-01 10:03 UTC, adityasharma7 commented on src/views/PurchaseOrder.vue
> +        const fieldMappingModal = await modalController.create({
```suggestion
        const createMappingModal = await modalController.create({
```

2023-02-01 10:03 UTC, adityasharma7 commented on src/views/SavedMappings.vue
> +        ...mapping
I think this might not be needed

2023-02-01 10:29 UTC, ymaheshwari1 commented on src/components/CreateMappingModal.vue
> +    generateUniqueMappingPrefId(): any {
Sir, as the id is required in the api when creating preference, so generating the id here.
Will create an issue to remove this code when the api will be updated.

2023-02-01 12:49 UTC, merged