fix: missing sku not displayed in completed tab after updating
hotwax/import pull request #169
Opened 2023-02-02 09:47 UTC by disha1202

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/import#contribution-guideline)

2023-02-02 13:45 UTC, ymaheshwari1 requested changes

2023-02-02 13:45 UTC, ymaheshwari1 commented on src/components/ProductPopover.vue
> +      this.store.dispatch('order/updatePurchaseOrders', this.purchaseOrders)
As we are deep cloning the value returned from getter, I think then we don't need to deep clone the original object in here https://github.com/hotwax/import/pull/169/files#diff-474eebde566a51c1cce273a03e682271d4d7d8d674218118ee580f38ecf32d90R68

2023-02-03 05:11 UTC, ymaheshwari1 requested changes

2023-02-03 05:11 UTC, ymaheshwari1 commented on src/components/MissingSkuModal.vue
> +        this.purchaseOrders.unidentifiedItems.map((unidentifiedItem: any) => {
Why we have used map here? As we are always updating a single product.

2023-02-03 07:06 UTC, adityasharma7 requested changes

2023-02-03 07:06 UTC, adityasharma7 commented on src/views/PurchaseOrderReview.vue
> +      this.purchaseOrders.parsed = this.purchaseOrders.original;
I think we should deep clone whenever we revert

2023-02-03 09:17 UTC, adityasharma7 approved these changes

2023-02-03 09:18 UTC, merged