Save button updated
hotwax/import pull request #236
Opened 2023-10-13 07:15 UTC by Killer2OP

### Related Issues

Closes #234 

### Short Description and Why It's Useful

the :disabled attribute of the <ion-fab-button> element is bound to the changesMade data property. If changesMade is false (indicating that there are no changes to update), the button will be disabled. When changes are detected and changesMade is set to true, the button will be enabled, allowing the user to save the changes.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/import#contribution-guideline)

2023-10-13 07:37 UTC, k2maan requested changes

2023-10-13 07:37 UTC, k2maan commented on src/components/MissingFacilitiesModal.vue
> +      this.changesMade = false;
The condition should be based on the itemsByFacilityId array.

2023-10-13 08:33 UTC, Killer2OP commented
@k2maan Review please..

2023-11-14 04:52 UTC, ymaheshwari1 approved these changes

2023-11-14 13:12 UTC, merged