Implemented: Scheduled restock functionality (#285)
hotwax/import pull request #286
Opened 2024-05-29 11:18 UTC by R-Sourabh

### Related Issues

#285 
### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/import#contribution-guideline)

2024-06-05 13:40 UTC, ymaheshwari1 requested changes

2024-06-05 13:40 UTC, ymaheshwari1 commented on .env.example
> +VUE_APP_MAPPING_RSTSTK={"productIdentification": { "label": "Product Identification", "required": true }, "facility": { "label": "Facility", "required": true }, "restockQuantity": { "label": "Restock
Remove facility from here as we do not make it required.

2024-06-05 13:40 UTC, ymaheshwari1 commented on src/components/CreateMappingModal.vue
> +      if (this.mappingType == 'RSTSTK') {
We don't need this logic anymore as we are only having required mappings in env

2024-06-05 13:40 UTC, ymaheshwari1 commented on src/store/modules/util/actions.ts
> +  async fetchProductStores({ state, commit }) {
Remove state as not used.

2024-06-05 13:40 UTC, ymaheshwari1 commented on src/store/modules/util/actions.ts
> +      "entityName": "ProductStore",
Pass fieldList as we only need specific fields in response like productStore name, id.

2024-06-05 13:40 UTC, ymaheshwari1 commented on src/views/Inventory.vue
> +.review{
Why we have changed selector here?

2024-06-06 09:58 UTC, ymaheshwari1 requested changes

2024-06-06 09:58 UTC, ymaheshwari1 commented on src/store/modules/util/index.ts
> +      productStores: []
Clear stored productStores and shopifyShops on logout

2024-06-06 09:58 UTC, ymaheshwari1 commented on src/views/ScheduledRestockReview.vue
> +    <ion-header :translucent="true">
Remove translucent as it only works in ios mode

2024-06-06 09:58 UTC, ymaheshwari1 commented on src/views/ScheduledRestockReview.vue
> +                    presentation="date-time"
Remove presentation as the default value is `date-time` only.

2024-06-06 09:58 UTC, ymaheshwari1 commented on src/views/ScheduledRestockReview.vue
> +        <p>{{ translate("No product found") }}</p>
```suggestion
        <p>{{ translate("No products found") }}</p>
```

2024-06-06 09:58 UTC, ymaheshwari1 commented on src/views/ScheduledRestockReview.vue
> +  name: 'ScheduledRestockDetail',
```suggestion
  name: 'ScheduledRestockReview',
```

2024-06-06 09:58 UTC, ymaheshwari1 commented on src/views/ScheduledRestockReview.vue
> +  // async beforeRouteLeave(to) {
Add this feature to not allow user to go back if there are unsaved changes.

2024-06-06 09:58 UTC, ymaheshwari1 commented on src/store/modules/stock/actions.ts
> +          'recurrenceTimeZone': this.state.user.current.usershipPackedOrdersTimeZone,
Why we have used `usershipPackedOrdersTimeZone` here?

2024-06-06 09:58 UTC, ymaheshwari1 commented on src/store/modules/stock/actions.ts
> +          'maxRecurrenceCount': '-1',
Remove maxRecurrenceCount as we want to schedule it only once.

2024-06-06 10:01 UTC, ymaheshwari1 requested changes

2024-06-06 10:01 UTC, ymaheshwari1 commented on src/store/modules/stock/actions.ts
> +        'JOB_NAME': restockName || state.schedule.restockName || `Created ${DateTime.fromMillis(+state.schedule.scheduledTime).toLocaleString(DateTime.DATETIME_MED)}`,
Change the time here to the current time instead of scheduledTime if the restockName is not found.

2024-06-06 10:45 UTC, ymaheshwari1 requested changes

2024-06-06 10:45 UTC, ymaheshwari1 commented on src/views/ScheduledRestock.vue
> +          <input @change="parse" ref="file" class="ion-hide" type="file" id="restockInputFile" placeholder=/>
Remove placeholder

2024-06-06 10:45 UTC, ymaheshwari1 commented on src/views/ScheduledRestock.vue
> +    await this.store.dispatch('util/fetchGoodIdentificationTypes');
Make this api calls in parallel as they are independent of each other.

2024-06-06 10:45 UTC, ymaheshwari1 commented on src/views/ScheduledRestock.vue
> +          this.selectedProductStoreId = this.productStores[0].productStoreId ? this.productStores[5].productStoreId : ''
```suggestion
          this.selectedProductStoreId = this.productStores.length ? this.productStores[0].productStoreId : ''
```

2024-06-06 10:45 UTC, ymaheshwari1 commented on src/views/ScheduledRestock.vue
> +    },
```suggestion
    async updateProductStore(productStoreId) {
      this.selectedShopifyShopId = ''
      this.fetchShopifyShops(productStoreId);
    },
```

2024-06-06 10:45 UTC, ymaheshwari1 commented on src/views/ScheduledRestock.vue
> +            <ion-select :label="translate('Product store')" interface="popover" :value="selectedProductStoreId" @ionChange="updateProductStore($event)">
```suggestion
            <ion-select :label="translate('Product store')" interface="popover" :value="selectedProductStoreId" @ionChange="updateProductStore($event.detail.value)">
```

2024-06-06 10:45 UTC, ymaheshwari1 commented on src/components/ScheduledRestockPopover.vue
> +      store
Return translate function from here.

2024-06-06 10:45 UTC, ymaheshwari1 commented on src/views/ScheduledRestock.vue
> +            <ion-select :label="translate('Product store')" interface="popover" :value="selectedProductStoreId" @ionChange="updateProductStore($event)">
Add a placeholder here as well, as you have added placeholders on facility and shopifyShop option

2024-06-06 10:45 UTC, ymaheshwari1 commented on src/views/ScheduledRestock.vue
> +      const areAllFieldsSelected = Object.values(this.fieldMapping).every(field => field !== "");
Add a loader as after clicking review it might take some time to move to the next page

2024-06-06 10:45 UTC, ymaheshwari1 commented on src/views/ScheduledRestockReview.vue
> +    await this.store.dispatch('util/fetchFacilities');
I think there is no need to fetch facilities here as we are already fetching them on the first page

2024-06-06 10:45 UTC, ymaheshwari1 commented on src/views/ScheduledRestockReview.vue
> +          viewSize: 100
Fetch only those fields which are required by passing fieldList.

2024-06-06 10:45 UTC, ymaheshwari1 commented on src/views/ScheduledRestockReview.vue
> +      this.schedule.shopId = this.shopifyShops[0].shopId ? this.shopifyShops[0].shopId : '';
```suggestion
      this.schedule.shopId = this.shopifyShops.length && this.shopifyShops[0]?.shopId ? this.shopifyShops[0].shopId : '';
```

2024-06-06 11:05 UTC, R-Sourabh commented on src/views/Inventory.vue
> +.review{
By mistake.

2024-06-10 06:25 UTC, ymaheshwari1 requested changes

2024-06-10 06:25 UTC, ymaheshwari1 commented on src/store/modules/stock/actions.ts
> +          commit(types.STOCK_JOBS_UPDATED, []);
Improve indentation

2024-06-10 06:25 UTC, ymaheshwari1 commented on src/store/modules/stock/actions.ts
> +    commit(types.STOCK_SCHEDULED_INFORMATION, {})
```suggestion
    commit(types.STOCK_SCHEDULED_INFORMATION, {
      scheduledTime: "",
      shopId: "",
      restockName: "",
      productStoreId: "",
      facilityId: ""
    })
```

2024-06-10 06:25 UTC, ymaheshwari1 commented on src/store/modules/stock/getters.ts
> +
Remove unwanted lines.

2024-06-10 09:57 UTC, ymaheshwari1 approved these changes

2024-06-10 09:57 UTC, merged