Implemented: Unified inventory upload(#304)
hotwax/import pull request #309
Opened 2024-12-30 13:55 UTC by R-Sourabh

### Related Issues

#304 

### Short Description and Why It's Useful

- Implemented the unified inventory upload by adding an `Inventory` menu item, which contains various options for uploading inventory.  
- Added 3 ways to upload inventory as `Exact ATP`, `Exact QOH`, and `Cycle Count`.
- Created a new page for `Scheduled Incoming Inventory`, which lists the scheduled inventory uploads. From that page, users can navigate to the `Scheduled Product Launch` page to schedule new inventory updates.  
- Added a `Launch Details` page that lists the details of upcoming inventory uploads. From this page, users can cancel the entire inventory, add new products to the shipment using a modal, or remove items from the shipment.  
- Added an `Adjust Inventory` page where users can upload files to update inventory. This page includes various cases based on the mode of execution of the `Process Bulk Imported Files` job.  
- Added a `History` page that displays the log history of the `MDM_INV_VARIANCE` configuration. Users can download the uploaded file, log file, and records of failed attempts.

### Screenshots of Visual Changes before/after (If There Are Any)

![Screenshot from 2024-12-30 18-56-57](https://github.com/user-attachments/assets/e5e5dafe-a2a5-4c80-8518-d448feeaf884)
![Screenshot from 2024-12-30 18-57-51](https://github.com/user-attachments/assets/85f6b087-064a-4f16-8344-5d6e01aa035b)
![Screenshot from 2024-12-30 18-58-08](https://github.com/user-attachments/assets/8f02bcaa-efe5-4849-8ec5-ac960715ef99)
![Screenshot from 2024-12-30 18-58-34](https://github.com/user-attachments/assets/676bc3b2-9878-4527-afac-7a4c7f8f90ac)
![Screenshot from 2024-12-30 18-58-47](https://github.com/user-attachments/assets/c8fddfc9-459a-4e4e-9419-36ce39ac964a)
![Screenshot from 2024-12-30 18-58-57](https://github.com/user-attachments/assets/97dbbaf3-a4b1-4f5a-afb7-53e28609ad59)
![Screenshot from 2024-12-30 19-07-30](https://github.com/user-attachments/assets/ae79366d-218e-4dc1-ac85-e6e6bf36cea6)
![Screenshot from 2024-12-30 19-07-47](https://github.com/user-attachments/assets/9c2a4106-263a-49c1-9f38-675adea48a1d)
![Screenshot from 2024-12-30 19-07-52](https://github.com/user-attachments/assets/5a661d22-ebcf-4571-9a11-9301b8ce956a)
### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/import#contribution-guideline)

2025-01-02 12:54 UTC, ymaheshwari1 requested changes

2025-01-06 05:36 UTC, ymaheshwari1 requested changes

2025-01-06 05:36 UTC, ymaheshwari1 commented on src/views/AdjustInventoryHistory.vue
> +          <ion-icon :icon="cloudUploadOutline"/>
Add slot end

2025-01-06 06:12 UTC, ymaheshwari1 requested changes

2025-01-06 06:17 UTC, ymaheshwari1 requested changes

2025-01-06 06:17 UTC, ymaheshwari1 commented on src/store/index.ts
> +    paths: ['user', 'util.productStores', 'util.statusDesc'],
Clear status desc data on logout, also check once if all the data is getting cleared on logout.

2025-01-06 06:33 UTC, ymaheshwari1 requested changes

2025-01-06 06:33 UTC, ymaheshwari1 commented on src/views/AdjustInventory.vue
> +                      const omsURL = (this.instanceUrl.startsWith('http') ? this.instanceUrl.replace(/\/api\/?|\/$/, "") : `https://${this.instanceUrl}.hotwax.io`) + `/commerce/control/ImportData?con
instanceUrl is not defined

2025-01-10 06:27 UTC, ymaheshwari1 requested changes

2025-01-10 06:27 UTC, ymaheshwari1 commented on src/views/AdjustInventory.vue
> +                {{ translate("Uploaded files will be processed in", { runTime: getRunTime() }) }}
Display runTime delta in the format like `in 25 minutes`.

2025-01-10 09:02 UTC, ymaheshwari1 requested changes

2025-01-10 09:02 UTC, ymaheshwari1 commented on src/store/modules/util/actions.ts
> +        commit(types.UTIL_SERVICE_STATUS_DESC_UPDATED, resp.data.docs);
Prepare the state with key value here itself and just use mutation for updating the value.
Use single mutation for updating and clearing state.

2025-01-10 09:02 UTC, ymaheshwari1 commented on src/store/modules/util/actions.ts
> +      if (resp.status === 200 && !hasError(resp) && resp.data.count) {
Remove 200 status check.

2025-01-10 10:44 UTC, ymaheshwari1 requested changes

2025-01-10 10:44 UTC, ymaheshwari1 commented on src/views/ScheduledIncomingInventory.vue
> +    updateJobsByStatus() {
```suggestion
    filterJobsByStatus() {
```

2025-01-10 10:48 UTC, R-Sourabh commented on src/views/UnifiedInventory.vue
> +            <ion-icon slot="icon-only" :icon="informationCircleOutline" />
@ymaheshwari1 We have added a Help modal that will open when this button is clicked.

2025-01-13 10:24 UTC, merged