Implemeted Static UI for displaying parsed csv and Implemented logic …
hotwax/import pull request #5
Opened 2022-02-23 13:46 UTC by disha1202

…to map parsed Csv and implemented order state(#22c8vf8)

2022-02-27 03:12 UTC, dt2patel requested changes

2022-02-27 03:12 UTC, dt2patel commented on src/views/OrderDetail.vue
> +.list-item{
this is ok for now but add a note that this code needs to be updated to use universal list item class

2022-02-28 09:47 UTC, adityasharma7 requested changes

2022-02-28 09:47 UTC, adityasharma7 commented on src/store/modules/order/OrderState.ts
> +    order: {
I think we should have state like this
```
list: {
        items: [],
        original: 0
      },
```

2022-02-28 09:47 UTC, adityasharma7 commented on src/store/modules/order/getters.ts
> +  getCsv(state){
```suggestion
  getOrdeItems(state){
```

2022-02-28 09:47 UTC, adityasharma7 commented on src/store/modules/order/actions.ts
> +  uploadCsv({commit}, payload){
```suggestion
  updateOrderList({commit}, payload){
```

2022-02-28 09:47 UTC, adityasharma7 commented on src/store/modules/order/mutation-types.ts
> +export const UPLOAD_CSV = SN_ORDER + '/UPLOAD_CSV'
```suggestion
export const ORDER_LIST_UPDATED = SN_ORDER + '/LIST_UPDATED'
```

2022-03-04 04:43 UTC, ymaheshwari1 requested changes

2022-03-04 04:43 UTC, ymaheshwari1 commented on src/router/index.ts
> +    name: 'Purchase Order Detail',
```suggestion
    name: 'PurchaseOrderDetail',
```

2022-03-04 04:43 UTC, ymaheshwari1 commented on src/store/actions.ts
> +}
Remove these unwanted changes.

2022-03-04 04:43 UTC, ymaheshwari1 commented on src/store/modules/order/actions.ts
> +      commit(types.UPLOAD_CSV,  payload );
```suggestion
      commit(types.UPLOAD_CSV, payload);
```

2022-03-04 04:43 UTC, ymaheshwari1 commented on src/store/modules/product/mutations.ts
> +    // TODO
I think we can remove these TODO.

2022-03-04 04:43 UTC, ymaheshwari1 commented on src/views/OrderDetail.vue
> +          <ion-button expand="block" fill="outline">Apply</ion-button>
Internationalize text.

2022-03-04 04:43 UTC, ymaheshwari1 commented on src/views/OrderDetail.vue
> +    components: {
Change indentation to 2 spaces.

2022-03-04 06:13 UTC, adityasharma7 commented
Changes merged with https://github.com/hotwax/import/pull/8. Closing

2022-03-04 06:13 UTC, closed without merging