[vuex] unknown action type: user/clearOrderList
hotwax/import pull request #72
Opened 2022-10-14 09:32 UTC by priyanshunema

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/import#contribution-guideline)

2022-10-14 09:35 UTC, ymaheshwari1 requested changes

2022-10-14 09:35 UTC, ymaheshwari1 commented on src/store/modules/user/actions.ts
> +    this.dispatch('order/clearOrderList');
Remove the extra space at the end of the line.

2022-10-14 10:56 UTC, priyanshunema commented
Sure

On Fri, Oct 14, 2022, 3:05 PM Yash Maheshwari ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/store/modules/user/actions.ts
> <https://github.com/hotwax/import/pull/72#discussion_r995558933>:
>
> > @@ -73,7 +73,7 @@ const actions: ActionTree<UserState, RootState> = {
>    async logout ({ commit }) {
>      // TODO add any other tasks if need
>      commit(types.USER_END_SESSION)
> -    this.dispatch('user/clearOrderList');
> +    this.dispatch('order/clearOrderList');
>
> Remove the extra space at the end of the line.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hotwax/import/pull/72#pullrequestreview-1142127861>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMXHXY3EBTDARGY3MQ7BRILWDESNVANCNFSM6AAAAAARFB4UTQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-14 10:15 UTC, adityasharma7 commented
@priyanshunema 

Your following commit is added to main
https://github.com/hotwax/import/commit/d8ef8f264f8c8a7985290ada185b522e029237ee

Closing as rest changes not needed

2022-11-14 10:15 UTC, closed without merging